PRGNAME ?= pcfx-headless
CC ?= gcc
CHD ?= YES
FAST_VIDEO ?= NO

INCLUDES = -Ipcfx-common/include -Ishell/headers -Ishell/video/headless -Ishell/audio -Ishell/scalers -Ishell/input/headless -Ishell/input -Ishell/menu -Ishell/emu -Imednafen -Imednafen/pcfx -Imednafen/sound -Imednafen/video -Imednafen/hw_cpu -Imednafen/hw_sound -I.
VIDEO_FORMAT ?= RGB565
DEFINES = -DLSB_FIRST -DNDEBUG -DWANT_STEREO_SOUND -DWANT_PCFX_EMU -DSIZEOF_DOUBLE=8 -DMEDNAFEN_VERSION=\"0.9.36.5\" -DPACKAGE=\"mednafen\" -DMEDNAFEN_VERSION_NUMERIC=9365 -DMPC_FIXED_POINT -DSTDC_HEADERS -D__STDC_LIMIT_MACROS -D_LOW_ACCURACY_ -DPACKAGE_VERSION=\"1.3.3\" -DHAVE_LROUND -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_SYS_PARAM_H -DPCFX_HEADLESS -DHAVE_HUC6273 -DPCFX_V810_ACCURATE_ONLY=1


ifeq ($(VIDEO_FORMAT),RGBA8888)
DEFINES += -DWANT_32BPP -DFRONTEND_SUPPORTS_RGBA8888
else ifeq ($(VIDEO_FORMAT),ARGB8888)
DEFINES += -DWANT_32BPP
else
DEFINES += -DWANT_16BPP -DFRONTEND_SUPPORTS_RGB565
endif

ifeq ($(CHD),YES)
INCLUDES += -Ideps/libchdr/include -Ideps/lzma-19.00/include
DEFINES += -DHAVE_CHD -D_7ZIP_ST
endif


ifeq ($(FAST_VIDEO), YES)
DEFINES += -DPCFX_FAST_VIDEO_DEFAULT=1
endif

# PROFILE=1 enables the V810 performance profiler (v810_profile.[ch]); off by default.
ifeq ($(PROFILE),1)
DEFINES += -DV810_PROFILE
endif
CFLAGS ?= -O2 -g3 -fno-common -Wall -Wextra -Wunused-value
CSTD ?= -std=gnu11
CFLAGS += $(INCLUDES) $(DEFINES)
LDFLAGS ?= -lz -lm

SRCDIR = ./headless ./shell/emu ./shell/video/headless ./shell/audio/headless ./shell/input/headless
SRCDIR += ./mednafen ./mednafen/cdrom ./mednafen/hw_sound/pce_psg ./mednafen/hw_video/huc6270 ./mednafen/pcfx ./mednafen/pcfx/huc6273 ./mednafen/pcfx/input ./mednafen/sound ./mednafen/hw_cpu/v810 ./mednafen/video
ifeq ($(CHD),YES)
SRCDIR += ./deps/libchdr/src ./deps/lzma-19.00/src
endif

VPATH = $(SRCDIR)
SRC_C = $(foreach dir,$(SRCDIR),$(wildcard $(dir)/*.c))
OBJ_C = $(notdir $(patsubst %.c,%.o,$(SRC_C)))
OBJS		= $(OBJ_C)

$(PRGNAME): $(OBJS)
	$(CC) $(CFLAGS) $(CSTD) -o $@ $^ $(LDFLAGS)

$(OBJ_C): %.o: %.c
	$(CC) $(CFLAGS) $(CSTD) -c -o $@ $<

.PHONY: clean clean-headless
clean: clean-headless

clean-headless:
	rm -f $(PRGNAME) $(OBJS)
