PRGNAME ?= pcfx-sdl3-ui
CC ?= gcc
CXX ?= g++
CHD ?= YES
FAST_VIDEO ?= NO
SDL3_CFLAGS ?= $(shell pkg-config --cflags sdl3 2>/dev/null || pkg-config --cflags SDL3 2>/dev/null)
SDL3_LIBS ?= $(shell pkg-config --libs sdl3 2>/dev/null || pkg-config --libs SDL3 2>/dev/null || echo -lSDL3)

INCLUDES = -Ilibretro-common/include -Ishell/headers -Ishell/video/headless -Ishell/audio -Ishell/scalers -Ishell/input/headless -Ishell/input -Ishell/menu -Ishell/emu -Imednafen -Imednafen/pcfx -Imednafen/sound -Imednafen/video -Imednafen/hw_cpu -Imednafen/hw_sound -I. $(SDL3_CFLAGS)
DEFINES = -DLSB_FIRST -DINLINE="inline" -DNDEBUG -DWANT_STEREO_SOUND -DWANT_16BPP -DFRONTEND_SUPPORTS_RGB565 -DWANT_PCFX_EMU -DSIZEOF_DOUBLE=8 -DMEDNAFEN_VERSION=\"0.9.36.5\" -DPACKAGE=\"mednafen\" -DMEDNAFEN_VERSION_NUMERIC=9365 -DMPC_FIXED_POINT -DSTDC_HEADERS -D__STDC_LIMIT_MACROS -D__LIBRETRO__ -D_LOW_ACCURACY_ -DPACKAGE_VERSION=\"1.3.3\" -DHAVE_LROUND -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_SYS_PARAM_H -DPCFX_HEADLESS -DHAVE_HUC6273

ifeq ($(CHD),YES)
INCLUDES += -Ideps/libchdr/include -Ideps/lzma-19.00/include
DEFINES += -DHAVE_CHD -D_7ZIP_ST
endif

ifeq ($(FAST_VIDEO),YES)
DEFINES += -DPCFX_FAST_VIDEO_DEFAULT=1
endif

CFLAGS ?= -O2 -g3 -fno-common -Wall -Wextra -Wunused-value
CFLAGS += $(INCLUDES) $(DEFINES)
CXXFLAGS ?= $(CFLAGS) -fno-rtti -fno-exceptions -std=gnu++14
LDFLAGS ?= -lz -lm $(SDL3_LIBS)

SRCDIR = ./headless ./sdl3 ./shell/emu ./shell/video/headless ./shell/audio/headless ./shell/input/headless
SRCDIR += ./mednafen ./mednafen/cdrom ./mednafen/hw_sound/pce_psg ./mednafen/hw_video/huc6270 ./mednafen/pcfx ./mednafen/pcfx/huc6273 ./mednafen/pcfx/input ./mednafen/sound ./mednafen/hw_cpu/v810 ./mednafen/video
SRCDIR += ./libretro-common/compat ./libretro-common/file ./libretro-common/streams ./libretro-common/string ./libretro-common/time ./libretro-common/vfs
ifeq ($(CHD),YES)
SRCDIR += ./deps/libchdr/src ./deps/lzma-19.00/src
endif

VPATH = $(SRCDIR)
SRC_C = $(foreach dir,$(SRCDIR),$(wildcard $(dir)/*.c))
SRC_CPP_ALL = $(foreach dir,$(SRCDIR),$(wildcard $(dir)/*.cpp))
SRC_CPP = $(filter-out ./headless/pcfx_headless_cli.cpp,$(SRC_CPP_ALL))
OBJ_C = $(notdir $(patsubst %.c,%.o,$(SRC_C)))
OBJ_CPP = $(notdir $(patsubst %.cpp,%.o,$(SRC_CPP)))
OBJS = $(OBJ_C) $(OBJ_CPP)

$(PRGNAME): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

$(OBJ_CPP): %.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

$(OBJ_C): %.o: %.c
	$(CC) $(CFLAGS) -std=gnu99 -c -o $@ $<

.PHONY: clean clean-sdl3
clean: clean-sdl3

clean-sdl3:
	rm -f $(PRGNAME) $(OBJS)
