CSTD ?= -std=gnu11
PRGNAME     = pcfx.elf
CC          = /opt/funkey-toolchain/usr/bin/arm-linux-gcc

#### Configuration

# Possible values : retrostone, rs97, rs90
PORT = funkey
# Possible values : alsa, oss, portaudio
SOUND_ENGINE = alsa
PROFILE = APPLY
CHD = NO
FAST_VIDEO ?= YES
DEBUG = 0

#### End of Configuration

GIT_VERSION := " $(shell git rev-parse --short HEAD || echo unknown)"

INCLUDES	= -Ipcfx-common/include -Isrc
INCLUDES	+= -Ishell/headers -Ishell/video/$(PORT) -Ishell/audio -Ishell/scalers -Ishell/input/sdl -Ishell/fonts -Ishell/menu
INCLUDES	+= -Imednafen -I./mednafen/vb -I./mednafen/sound -I. -Ishell/emu -Imednafen/include -Ishell/input -Imednafen/video -Imednafen/hw_cpu
INCLUDES	+= -Ipcfx-common/include  -Imednafen/hw_sound

DEFINES		= -DLSB_FIRST -DNDEBUG -DFORCE_FRAMESKIP
DEFINES		+= -DWANT_16BPP -DFRONTEND_SUPPORTS_RGB565
DEFINES		+= -DSIZEOF_DOUBLE=4 -DMEDNAFEN_VERSION=\"0.9.36.5\" -DPACKAGE=\"mednafen\" -DMEDNAFEN_VERSION_NUMERIC=9365 -DMPC_FIXED_POINT -DSTDC_HEADERS -D__STDC_LIMIT_MACROS -D_LOW_ACCURACY_
DEFINES		+= -DPACKAGE_VERSION=\"1.3.3\" -DHAVE_LROUND -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_SYS_PARAM_H -DFUNKEY -DSCALING_SOFTWARE
DEFINES		+= -DPCFX_V810_FAST_ONLY=1 -DPCFX_HIGH_DOTCLOCK_WIDTH=256

ifeq ($(CHD), YES)
INCLUDES 		+= -Ideps/libchdr/include -Ideps/lzma-19.00/include
DEFINES			+= -DHAVE_CHD -D_7ZIP_ST
endif

ifeq ($(FAST_VIDEO), YES)
DEFINES += -DPCFX_FAST_VIDEO_DEFAULT=1
endif

ifeq ($(DEBUG), YES)

CFLAGS		= -Wall -Wextra -O0 -g3
CFLAGS		+= $(INCLUDES) $(DEFINES)
LDFLAGS     = -lc -lgcc -lm -lSDL -lasound -lz
else

CFLAGS		= -Wall -Wextra -Ofast -fdata-sections -ffunction-sections -fsingle-precision-constant -freorder-functions -fno-math-errno -fgcse-las -fgcse-sm -fmerge-all-constants -flto -fno-PIC -freorder-functions
CFLAGS		+= $(INCLUDES) $(DEFINES) -fno-math-errno -fgcse-las -fgcse-sm -fmerge-all-constants -fno-ident -fno-stack-protector -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -freorder-functions -freorder-blocks
# -freorder-blocks-and-partition -freorder-functions

LDFLAGS     = -nodefaultlibs -lc -lgcc -lm -lSDL -lasound -lz -Wl,-z,norelro -Wl,--hash-style=gnu -Wl,--build-id=none -Wl,-O1,--sort-common,--as-needed,--gc-sections -flto -no-pie -s
endif



ifeq ($(PROFILE), YES)
CFLAGS 		+= -fprofile-generate -fprofile-dir=/mnt/pcfxg
else ifeq ($(PROFILE), APPLY)
CFLAGS		+= -fprofile-use -fbranch-probabilities
endif

ifeq ($(SOUND_ENGINE), alsa)
LDFLAGS 		+= -lasound
endif
ifeq ($(SOUND_ENGINE), portaudio)
LDFLAGS 		+= -lasound -lportaudio
endif

ifeq ($(PROFILE), YES)
LDFLAGS 	+= -lgcov
endif

# Files to be compiled
SRCDIR 		=  ./src ./shell ./shell/emu ./shell/menu
SRCDIR		+= ./shell/input/sdl/ ./shell/video/$(PORT) ./shell/audio/$(SOUND_ENGINE)
SRCDIR		+= ./mednafen ./mednafen/cdrom ./mednafen/hw_sound/pce_psg ./mednafen/hw_video/huc6270 ./mednafen/pcfx ./mednafen/pcfx/input ./mednafen/sound ./mednafen/hw_cpu/v810 ./mednafen/hw_cpu/v810/fpu-new ./mednafen/video
SRCDIR		+= ./pcfx-common/compat
ifeq ($(CHD), YES)
SRCDIR		+= ./deps/libchdr/src ./deps/lzma-19.00/src
endif


VPATH		= $(SRCDIR)
SRC_C		= $(foreach dir, $(SRCDIR), $(wildcard $(dir)/*.c))
OBJ_C		= $(notdir $(patsubst %.c, %.o, $(SRC_C)))
OBJS		= $(OBJ_C)

# Rules to make executable
$(PRGNAME): $(OBJS)
	$(CC) $(CFLAGS) $(CSTD) -o $(PRGNAME) $^ $(LDFLAGS)

$(OBJ_C) : %.o : %.c
	$(CC) $(CFLAGS) $(CSTD) -c -o $@ $<

clean:
	rm -f $(PRGNAME)$(EXESUFFIX) *.o
