#!/bin/sh

mkdir -p opk
cp ./pcfx.elf opk/pcfx.elf
cp ./pcfx.png opk/pcfx.png
cp ./COPYING opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=PCFXEmu
Comment=Needs pcfx.rom in $HOME/.pcfxemu
Exec=pcfx.elf %f
Icon=pcfx
Terminal=false
Type=Application
Categories=emulators;
MimeType=application/x-cue;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk pcfxemu_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
